---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cespidh/public_html/cms_prueba_v2
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R BaseDatos $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp * $DEPLOYPATH