-- MySQL Script generated by MySQL Workbench
-- Thu Apr  7 00:22:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cespidh_v1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cespidh_v1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cespidh_v1` DEFAULT CHARACTER SET latin1 ;
USE `cespidh_v1` ;

-- -----------------------------------------------------
-- Table `cespidh_v1`.`documento_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`documento_tipo` (
  `id_tipo` INT(11) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `plantilla` TEXT NULL DEFAULT NULL,
  `abreviacion` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`documento_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`documento_estado` (
  `id_estado` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`documento` (
  `id_documento` INT(11) NOT NULL,
  `id_tipo` INT(11) NOT NULL COMMENT 'derecho de peticion, denuncia, etc',
  `id_estado` INT(11) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_documento_a_tipo_idx` (`id_tipo` ASC) ,
  INDEX `fk_documento_estado_idx` (`id_estado` ASC) ,
  INDEX `fk_documento_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_documento_a_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `cespidh_v1`.`documento_tipo` (`id_tipo`),
  CONSTRAINT `fk_documento_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `cespidh_v1`.`documento_estado` (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`work_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`work_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`formularios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`formularios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documento_tipo_id_tipo` INT(11) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formulario_prueba_documento_tipo1_idx` (`documento_tipo_id_tipo` ASC) ,
  CONSTRAINT `fk_formulario_prueba_documento_tipo1`
    FOREIGN KEY (`documento_tipo_id_tipo`)
    REFERENCES `cespidh_v1`.`documento_tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`secciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `formulario_prueba_id` INT NOT NULL,
  `title` VARCHAR(60) NULL DEFAULT NULL,
  `orden` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_secciones_formulario_prueba1_idx` (`formulario_prueba_id` ASC) ,
  CONSTRAINT `fk_secciones_formulario_prueba1`
    FOREIGN KEY (`formulario_prueba_id`)
    REFERENCES `cespidh_v1`.`formularios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`tipo_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`tipo_pregunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL COMMENT '1 - Pregunta abierta\\n2 - Select\\n3 - Radio\\n4 - Checkbox\\n5 - Lista texto\\n6 - Lista texto y Documento\\n7 - Derechos',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`preguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `secciones_id` INT NOT NULL,
  `tipo_pregunta_id` INT NOT NULL,
  `formulario_id` INT NULL DEFAULT NULL,
  `pregunta` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `pregunta_padre_id` INT NULL DEFAULT NULL,
  `complemento` TEXT NULL DEFAULT NULL,
  `orden` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preguntas_secciones1_idx` (`secciones_id` ASC) ,
  INDEX `fk_preguntas_tipo_pregunta1_idx` (`tipo_pregunta_id` ASC) ,
  INDEX `fk_preguntas_formularios_idx` (`formulario_id` ASC) ,
  CONSTRAINT `fk_preguntas_secciones1`
    FOREIGN KEY (`secciones_id`)
    REFERENCES `cespidh_v1`.`secciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preguntas_tipo_pregunta1`
    FOREIGN KEY (`tipo_pregunta_id`)
    REFERENCES `cespidh_v1`.`tipo_pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preguntas_formularios`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `cespidh_v1`.`secciones` (`formulario_prueba_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`pregunta_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`pregunta_detalle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preguntas_id` INT NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pregunta_detalle_preguntas1_idx` (`preguntas_id` ASC) ,
  CONSTRAINT `fk_pregunta_detalle_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `cespidh_v1`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`work` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL DEFAULT NULL,
  `finish_at` DATETIME NULL DEFAULT NULL,
  `observation` TEXT NULL DEFAULT NULL,
  `document` VARCHAR(45) NULL DEFAULT NULL,
  `documento_id_documento` INT(11) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  `work_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_work_documento1_idx` (`documento_id_documento` ASC) ,
  INDEX `fk_work_users1_idx` (`users_id` ASC) ,
  INDEX `fk_work_work_type1_idx` (`work_type_id` ASC) ,
  CONSTRAINT `fk_work_documento1`
    FOREIGN KEY (`documento_id_documento`)
    REFERENCES `cespidh_v1`.`documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_work_type1`
    FOREIGN KEY (`work_type_id`)
    REFERENCES `cespidh_v1`.`work_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`respuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preguntas_id` INT NOT NULL,
  `pregunta_detalle_id` INT NOT NULL,
  `documento_id_documento` INT(11) NOT NULL,
  `formulario_id` INT NULL DEFAULT NULL,
  `secciones_id` INT NULL DEFAULT NULL,
  `respuesta` VARCHAR(45) NULL DEFAULT NULL,
  `documento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_respuestas_preguntas1_idx` (`preguntas_id` ASC) ,
  INDEX `fk_respuestas_pregunta_detalle1_idx` (`pregunta_detalle_id` ASC) ,
  INDEX `fk_respuestas_formulario_idx` (`formulario_id` ASC) ,
  INDEX `fk_respuesta_secciones_idx` (`secciones_id` ASC) ,
  INDEX `fk_respuestas_documento1_idx` (`documento_id_documento` ASC) ,
  CONSTRAINT `fk_respuestas_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `cespidh_v1`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_pregunta_detalle1`
    FOREIGN KEY (`pregunta_detalle_id`)
    REFERENCES `cespidh_v1`.`pregunta_detalle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_formulario`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `cespidh_v1`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuesta_secciones`
    FOREIGN KEY (`secciones_id`)
    REFERENCES `cespidh_v1`.`preguntas` (`secciones_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_documento1`
    FOREIGN KEY (`documento_id_documento`)
    REFERENCES `cespidh_v1`.`documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
