-- MySQL Script generated by MySQL Workbench
-- Thu Apr  7 22:20:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`configurations` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_app` VARCHAR(45) NOT NULL,
  `icon_app` VARCHAR(30) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `intro` TEXT NULL DEFAULT NULL,
  `footer` TEXT NULL DEFAULT NULL,
  `meta_description` TEXT NULL DEFAULT NULL,
  `meta_keywords` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`documento_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documento_tipo` (
  `id_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `plantilla` TEXT NULL DEFAULT NULL,
  `abreviacion` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`documento_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documento_estado` (
  `id_estado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `orden` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo_etnia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupo_etnia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `orden` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(40) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'inactive',
  `photo` VARCHAR(100) NULL DEFAULT NULL,
  `role_id` INT(11) UNSIGNED NOT NULL,
  `genero_id` INT NOT NULL,
  `grupo_etnia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_role_id_foreign` (`role_id` ASC) VISIBLE,
  INDEX `fk_users_genero1_idx` (`genero_id` ASC) VISIBLE,
  INDEX `fk_users_grupo_etnia1_idx` (`grupo_etnia_id` ASC) VISIBLE,
  CONSTRAINT `users_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`id`),
  CONSTRAINT `fk_users_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `mydb`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_grupo_etnia1`
    FOREIGN KEY (`grupo_etnia_id`)
    REFERENCES `mydb`.`grupo_etnia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documento` (
  `id_documento` INT(11) NOT NULL AUTO_INCREMENT,
  `id_tipo` INT(11) NOT NULL COMMENT 'derecho de peticion, denuncia, etc',
  `id_estado` INT(11) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_documento_a_tipo_idx` (`id_tipo` ASC) VISIBLE,
  INDEX `fk_documento_estado_idx` (`id_estado` ASC) VISIBLE,
  INDEX `fk_documento_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_documento_a_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `mydb`.`documento_tipo` (`id_tipo`),
  CONSTRAINT `fk_documento_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `mydb`.`documento_estado` (`id_estado`),
  CONSTRAINT `fk_documento_user`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`formularios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formularios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `documento_tipo_id_tipo` INT(11) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formulario_prueba_documento_tipo1_idx` (`documento_tipo_id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_formulario_prueba_documento_tipo1`
    FOREIGN KEY (`documento_tipo_id_tipo`)
    REFERENCES `mydb`.`documento_tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menus` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `option` VARCHAR(40) NOT NULL,
  `url` VARCHAR(100) NOT NULL,
  `icon` VARCHAR(20) NULL DEFAULT NULL,
  `position` INT(3) NULL DEFAULT NULL,
  `type` ENUM('primario', 'secundario') NOT NULL DEFAULT 'primario',
  `references` INT(11) NULL DEFAULT NULL,
  `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  `component` ENUM('table', 'controller') NOT NULL DEFAULT 'table',
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `table` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`migrations` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `version` VARCHAR(255) NOT NULL,
  `class` TEXT NOT NULL,
  `group` VARCHAR(255) NOT NULL,
  `namespace` VARCHAR(255) NOT NULL,
  `time` INT(11) NOT NULL,
  `batch` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notifications` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `body` TEXT NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  `color` ENUM('', 'cyan', 'amber', 'orange', 'purple', 'red darken-1') NOT NULL DEFAULT 'cyan',
  `created_at` DATETIME NULL DEFAULT NULL,
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `notifications_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `notifications_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INT(11) UNSIGNED NOT NULL,
  `menu_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `permissions_role_id_foreign` (`role_id` ASC) VISIBLE,
  INDEX `permissions_menu_id_foreign` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `permissions_menu_id_foreign`
    FOREIGN KEY (`menu_id`)
    REFERENCES `mydb`.`menus` (`id`),
  CONSTRAINT `permissions_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`secciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `formulario_prueba_id` INT(11) NOT NULL,
  `title` VARCHAR(60) NULL DEFAULT NULL,
  `orden` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_secciones_formulario_prueba1_idx` (`formulario_prueba_id` ASC) VISIBLE,
  CONSTRAINT `fk_secciones_formulario_prueba1`
    FOREIGN KEY (`formulario_prueba_id`)
    REFERENCES `mydb`.`formularios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_pregunta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT NULL COMMENT '1 - Pregunta abierta\\\\n2 - Select\\\\n3 - Radio\\\\n4 - Checkbox\\\\n5 - Lista texto\\\\n6 - Lista texto y Documento\\\\n7 - Derechos',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`preguntas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `secciones_id` INT(11) NOT NULL,
  `tipo_pregunta_id` INT(11) NOT NULL,
  `formulario_id` INT(11) NULL DEFAULT NULL,
  `pregunta` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `pregunta_padre_id` INT(11) NULL DEFAULT NULL,
  `complemento` TEXT NULL DEFAULT NULL,
  `orden` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preguntas_secciones1_idx` (`secciones_id` ASC) VISIBLE,
  INDEX `fk_preguntas_tipo_pregunta1_idx` (`tipo_pregunta_id` ASC) VISIBLE,
  INDEX `fk_preguntas_formularios_idx` (`formulario_id` ASC) VISIBLE,
  CONSTRAINT `fk_preguntas_formularios`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `mydb`.`secciones` (`formulario_prueba_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preguntas_secciones1`
    FOREIGN KEY (`secciones_id`)
    REFERENCES `mydb`.`secciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preguntas_tipo_pregunta1`
    FOREIGN KEY (`tipo_pregunta_id`)
    REFERENCES `mydb`.`tipo_pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pregunta_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pregunta_detalle` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `preguntas_id` INT(11) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pregunta_detalle_preguntas1_idx` (`preguntas_id` ASC) VISIBLE,
  CONSTRAINT `fk_pregunta_detalle_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `mydb`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuestas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `preguntas_id` INT(11) NOT NULL,
  `pregunta_detalle_id` INT(11) NOT NULL,
  `documento_id_documento` INT(11) NOT NULL,
  `formulario_id` INT(11) NULL DEFAULT NULL,
  `secciones_id` INT(11) NULL DEFAULT NULL,
  `respuesta` VARCHAR(45) NULL DEFAULT NULL,
  `documento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_respuestas_preguntas1_idx` (`preguntas_id` ASC) VISIBLE,
  INDEX `fk_respuestas_pregunta_detalle1_idx` (`pregunta_detalle_id` ASC) VISIBLE,
  INDEX `fk_respuestas_formulario_idx` (`formulario_id` ASC) VISIBLE,
  INDEX `fk_respuesta_secciones_idx` (`secciones_id` ASC) VISIBLE,
  INDEX `fk_respuestas_documento1_idx` (`documento_id_documento` ASC) VISIBLE,
  CONSTRAINT `fk_respuesta_secciones`
    FOREIGN KEY (`secciones_id`)
    REFERENCES `mydb`.`preguntas` (`secciones_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_documento1`
    FOREIGN KEY (`documento_id_documento`)
    REFERENCES `mydb`.`documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_formulario`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `mydb`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_pregunta_detalle1`
    FOREIGN KEY (`pregunta_detalle_id`)
    REFERENCES `mydb`.`pregunta_detalle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `mydb`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`work_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`work_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`work` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL DEFAULT NULL,
  `finish_at` DATETIME NULL DEFAULT NULL,
  `observation` TEXT NULL DEFAULT NULL,
  `document` VARCHAR(45) NULL DEFAULT NULL,
  `documento_id_documento` INT(11) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  `work_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_work_documento1_idx` (`documento_id_documento` ASC) VISIBLE,
  INDEX `fk_work_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_work_work_type1_idx` (`work_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_work_documento1`
    FOREIGN KEY (`documento_id_documento`)
    REFERENCES `mydb`.`documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_work_type1`
    FOREIGN KEY (`work_type_id`)
    REFERENCES `mydb`.`work_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
