-- MySQL Script generated by MySQL Workbench
-- Wed Apr  6 23:58:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cespidh_v1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cespidh_v1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cespidh_v1` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema cespidh_cms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cespidh_cms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cespidh_cms` DEFAULT CHARACTER SET latin1 ;
USE `cespidh_v1` ;

-- -----------------------------------------------------
-- Table `cespidh_v1`.`configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`configurations` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name_app` VARCHAR(45) NOT NULL,
  `icon_app` VARCHAR(30) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `intro` TEXT NULL DEFAULT NULL,
  `footer` TEXT NULL DEFAULT NULL,
  `meta_description` TEXT NULL DEFAULT NULL,
  `meta_keywords` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`menus` (
  `id` INT(11) UNSIGNED NOT NULL,
  `option` VARCHAR(40) NOT NULL,
  `url` VARCHAR(100) NOT NULL,
  `icon` VARCHAR(20) NULL DEFAULT NULL,
  `position` INT(3) NULL DEFAULT NULL,
  `type` ENUM('primario', 'secundario') NOT NULL DEFAULT 'primario',
  `references` INT(11) NULL DEFAULT NULL,
  `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  `component` ENUM('table', 'controller') NOT NULL DEFAULT 'table',
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `table` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`migrations` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `version` VARCHAR(255) NOT NULL,
  `class` TEXT NOT NULL,
  `group` VARCHAR(255) NOT NULL,
  `namespace` VARCHAR(255) NOT NULL,
  `time` INT(11) NOT NULL,
  `batch` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`roles` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`solicitante_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`solicitante_genero` (
  `id_genero` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`solicitante_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`solicitante_grupo` (
  `id_grupo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`users` (
  `id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(40) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'inactive',
  `photo` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `role_id` INT(11) UNSIGNED NOT NULL,
  `solicitante_genero_id_genero` INT(11) NOT NULL,
  `solicitante_grupo_id_grupo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_role_id_foreign` (`role_id` ASC) VISIBLE,
  INDEX `fk_users_solicitante_genero1_idx` (`solicitante_genero_id_genero` ASC) VISIBLE,
  INDEX `fk_users_solicitante_grupo1_idx` (`solicitante_grupo_id_grupo` ASC) VISIBLE,
  CONSTRAINT `users_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `cespidh_v1`.`roles` (`id`),
  CONSTRAINT `fk_users_solicitante_genero1`
    FOREIGN KEY (`solicitante_genero_id_genero`)
    REFERENCES `cespidh_cms`.`solicitante_genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_solicitante_grupo1`
    FOREIGN KEY (`solicitante_grupo_id_grupo`)
    REFERENCES `cespidh_cms`.`solicitante_grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`notifications` (
  `id` INT(11) UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `body` TEXT NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  `color` ENUM('', 'cyan', 'amber', 'orange', 'purple', 'red darken-1') NOT NULL DEFAULT 'cyan',
  `created_at` DATETIME NULL DEFAULT NULL,
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `notifications_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `notifications_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `cespidh_v1`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`permissions` (
  `id` INT(11) UNSIGNED NOT NULL,
  `role_id` INT(11) UNSIGNED NOT NULL,
  `menu_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `permissions_role_id_foreign` (`role_id` ASC) VISIBLE,
  INDEX `permissions_menu_id_foreign` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `permissions_menu_id_foreign`
    FOREIGN KEY (`menu_id`)
    REFERENCES `cespidh_v1`.`menus` (`id`),
  CONSTRAINT `permissions_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `cespidh_v1`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`documento_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`documento_tipo` (
  `id_tipo` INT(11) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `plantilla` TEXT NULL,
  `abreviacion` VARCHAR(4) NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`documento_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`documento_estado` (
  `id_estado` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`documento` (
  `id_documento` INT(11) NOT NULL,
  `id_tipo` INT(11) NOT NULL COMMENT 'derecho de peticion, denuncia, etc',
  `id_estado` INT(11) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_documento_a_tipo_idx` (`id_tipo` ASC) VISIBLE,
  INDEX `fk_documento_estado_idx` (`id_estado` ASC) VISIBLE,
  INDEX `fk_documento_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_documento_a_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `cespidh_cms`.`documento_tipo` (`id_tipo`),
  CONSTRAINT `fk_documento_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `cespidh_cms`.`documento_estado` (`id_estado`),
  CONSTRAINT `fk_documento_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cespidh_v1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`work_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`work_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`work` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL,
  `finish_at` DATETIME NULL,
  `observation` TEXT NULL,
  `document` VARCHAR(45) NULL,
  `documento_id_documento` INT(11) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  `work_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_work_documento1_idx` (`documento_id_documento` ASC) VISIBLE,
  INDEX `fk_work_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_work_work_type1_idx` (`work_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_work_documento1`
    FOREIGN KEY (`documento_id_documento`)
    REFERENCES `cespidh_cms`.`documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cespidh_v1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_work_type1`
    FOREIGN KEY (`work_type_id`)
    REFERENCES `cespidh_cms`.`work_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`documento` (
  `id_documento` INT(11) NOT NULL,
  `id_tipo` INT(11) NOT NULL COMMENT 'derecho de peticion, denuncia, etc',
  `id_estado` INT(11) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_documento_a_tipo_idx` (`id_tipo` ASC) VISIBLE,
  INDEX `fk_documento_estado_idx` (`id_estado` ASC) VISIBLE,
  INDEX `fk_documento_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_documento_a_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `cespidh_cms`.`documento_tipo` (`id_tipo`),
  CONSTRAINT `fk_documento_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `cespidh_cms`.`documento_estado` (`id_estado`),
  CONSTRAINT `fk_documento_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cespidh_v1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`work_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`work_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`formularios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`formularios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documento_tipo_id_tipo` INT(11) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formulario_prueba_documento_tipo1_idx` (`documento_tipo_id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_formulario_prueba_documento_tipo1`
    FOREIGN KEY (`documento_tipo_id_tipo`)
    REFERENCES `cespidh_cms`.`documento_tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`secciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `formulario_prueba_id` INT NOT NULL,
  `title` VARCHAR(60) NULL,
  `orden` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_secciones_formulario_prueba1_idx` (`formulario_prueba_id` ASC) VISIBLE,
  CONSTRAINT `fk_secciones_formulario_prueba1`
    FOREIGN KEY (`formulario_prueba_id`)
    REFERENCES `cespidh_cms`.`formularios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`tipo_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`tipo_pregunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL COMMENT '1 - Pregunta abierta\n2 - Select\n3 - Radio\n4 - Checkbox\n5 - Lista texto\n6 - Lista texto y Documento\n7 - Derechos',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`preguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `secciones_id` INT NOT NULL,
  `tipo_pregunta_id` INT NOT NULL,
  `formulario_id` INT NULL,
  `pregunta` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `pregunta_padre_id` INT NULL,
  `complemento` TEXT NULL,
  `orden` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preguntas_secciones1_idx` (`secciones_id` ASC) VISIBLE,
  INDEX `fk_preguntas_tipo_pregunta1_idx` (`tipo_pregunta_id` ASC) VISIBLE,
  INDEX `fk_preguntas_formularios_idx` (`formulario_id` ASC) VISIBLE,
  CONSTRAINT `fk_preguntas_secciones1`
    FOREIGN KEY (`secciones_id`)
    REFERENCES `cespidh_cms`.`secciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preguntas_tipo_pregunta1`
    FOREIGN KEY (`tipo_pregunta_id`)
    REFERENCES `cespidh_cms`.`tipo_pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preguntas_formularios`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `cespidh_cms`.`secciones` (`formulario_prueba_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`pregunta_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`pregunta_detalle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preguntas_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pregunta_detalle_preguntas1_idx` (`preguntas_id` ASC) VISIBLE,
  CONSTRAINT `fk_pregunta_detalle_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `cespidh_cms`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`respuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preguntas_id` INT NOT NULL,
  `pregunta_detalle_id` INT NOT NULL,
  `documento_id_documento` INT(11) NOT NULL,
  `formulario_id` INT NULL,
  `secciones_id` INT NULL,
  `respuesta` VARCHAR(45) NULL,
  `documento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_respuestas_preguntas1_idx` (`preguntas_id` ASC) VISIBLE,
  INDEX `fk_respuestas_pregunta_detalle1_idx` (`pregunta_detalle_id` ASC) VISIBLE,
  INDEX `fk_respuestas_formulario_idx` (`formulario_id` ASC) VISIBLE,
  INDEX `fk_respuesta_secciones_idx` (`secciones_id` ASC) VISIBLE,
  INDEX `fk_respuestas_documento1_idx` (`documento_id_documento` ASC) VISIBLE,
  CONSTRAINT `fk_respuestas_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `cespidh_cms`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_pregunta_detalle1`
    FOREIGN KEY (`pregunta_detalle_id`)
    REFERENCES `cespidh_cms`.`pregunta_detalle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_formulario`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `cespidh_cms`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuesta_secciones`
    FOREIGN KEY (`secciones_id`)
    REFERENCES `cespidh_cms`.`preguntas` (`secciones_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_documento1`
    FOREIGN KEY (`documento_id_documento`)
    REFERENCES `cespidh_cms`.`documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`documento_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`documento_tipo` (
  `id_tipo` INT(11) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `plantilla` TEXT NULL,
  `abreviacion` VARCHAR(4) NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`documento_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`documento_estado` (
  `id_estado` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`formularios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`formularios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documento_tipo_id_tipo` INT(11) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formulario_prueba_documento_tipo1_idx` (`documento_tipo_id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_formulario_prueba_documento_tipo1`
    FOREIGN KEY (`documento_tipo_id_tipo`)
    REFERENCES `cespidh_cms`.`documento_tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`secciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `formulario_prueba_id` INT NOT NULL,
  `title` VARCHAR(60) NULL,
  `orden` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_secciones_formulario_prueba1_idx` (`formulario_prueba_id` ASC) VISIBLE,
  CONSTRAINT `fk_secciones_formulario_prueba1`
    FOREIGN KEY (`formulario_prueba_id`)
    REFERENCES `cespidh_cms`.`formularios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`preguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `secciones_id` INT NOT NULL,
  `tipo_pregunta_id` INT NOT NULL,
  `formulario_id` INT NULL,
  `pregunta` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `pregunta_padre_id` INT NULL,
  `complemento` TEXT NULL,
  `orden` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preguntas_secciones1_idx` (`secciones_id` ASC) VISIBLE,
  INDEX `fk_preguntas_tipo_pregunta1_idx` (`tipo_pregunta_id` ASC) VISIBLE,
  INDEX `fk_preguntas_formularios_idx` (`formulario_id` ASC) VISIBLE,
  CONSTRAINT `fk_preguntas_secciones1`
    FOREIGN KEY (`secciones_id`)
    REFERENCES `cespidh_cms`.`secciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preguntas_tipo_pregunta1`
    FOREIGN KEY (`tipo_pregunta_id`)
    REFERENCES `cespidh_cms`.`tipo_pregunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preguntas_formularios`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `cespidh_cms`.`secciones` (`formulario_prueba_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`tipo_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`tipo_pregunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL COMMENT '1 - Pregunta abierta\n2 - Select\n3 - Radio\n4 - Checkbox\n5 - Lista texto\n6 - Lista texto y Documento\n7 - Derechos',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`pregunta_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`pregunta_detalle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preguntas_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pregunta_detalle_preguntas1_idx` (`preguntas_id` ASC) VISIBLE,
  CONSTRAINT `fk_pregunta_detalle_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `cespidh_cms`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`solicitante_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`solicitante_genero` (
  `id_genero` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_v1`.`solicitante_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_v1`.`solicitante_grupo` (
  `id_grupo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `cespidh_cms` ;

-- -----------------------------------------------------
-- Table `cespidh_cms`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`archivo` (
  `id_archivo` INT(11) NOT NULL,
  `nombre_documento` VARCHAR(255) NULL DEFAULT NULL,
  `archivo` VARCHAR(255) NULL DEFAULT NULL,
  `id_documento` INT(11) NOT NULL,
  PRIMARY KEY (`id_archivo`),
  INDEX `id_documento` (`id_documento` ASC) VISIBLE,
  CONSTRAINT `archivo_ibfk_1`
    FOREIGN KEY (`id_documento`)
    REFERENCES `cespidh_cms`.`documento` (`id_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`formulario` (
  `id_formulario` INT(11) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `titulo_seccion` VARCHAR(255) NULL DEFAULT NULL,
  `titulo_seccion2` VARCHAR(255) NULL DEFAULT NULL,
  `titulo_seccion3` VARCHAR(255) NULL DEFAULT NULL,
  `documento_tipo_id_tipo` INT(11) NOT NULL,
  PRIMARY KEY (`id_formulario`),
  INDEX `fk_formulario_documento_tipo1_idx` (`documento_tipo_id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_formulario_documento_tipo1`
    FOREIGN KEY (`documento_tipo_id_tipo`)
    REFERENCES `cespidh_cms`.`documento_tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`campo` (
  `id_campo` INT(11) NOT NULL,
  `id_formulario` INT(11) NOT NULL,
  `nombre_campo` VARCHAR(255) NOT NULL,
  `es_obligatorio` ENUM('Si', 'No') NOT NULL,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `titulo_ventana` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion_ventana` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_campo`),
  INDEX `fk_campos_id_formulario_idx` (`id_formulario` ASC) VISIBLE,
  CONSTRAINT `fk_campos_id_formulario`
    FOREIGN KEY (`id_formulario`)
    REFERENCES `cespidh_cms`.`formulario` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`cms_iplanet_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`cms_iplanet_config` (
  `id` INT(11) NOT NULL,
  `conf_date` DATETIME NOT NULL,
  `conf_path` VARCHAR(100) NULL DEFAULT NULL,
  `conf_web` VARCHAR(100) NULL DEFAULT NULL,
  `conf_mail` VARCHAR(100) NOT NULL,
  `conf_comp` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`cms_iplanet_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`cms_iplanet_menu` (
  `menu_id` INT(11) NOT NULL,
  `menu_title` VARCHAR(40) NOT NULL,
  `menu_url` VARCHAR(80) NOT NULL,
  `menu_icon` VARCHAR(30) NOT NULL,
  `menu_post` INT(11) NOT NULL DEFAULT '0' COMMENT 'POSICION DE MENU',
  `menu_type` ENUM('Primario', 'Secundario') NOT NULL,
  `menu_refe` INT(11) NOT NULL DEFAULT '0',
  `menu_esta` ENUM('Si', 'No') NOT NULL DEFAULT 'Si' COMMENT 'ACTIVO  O INACTIVO',
  `menu_table_title` VARCHAR(50) NOT NULL,
  `menu_table_description` VARCHAR(255) NOT NULL,
  `menu_table_name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`cms_iplanet_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`cms_iplanet_permission` (
  `permission_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  `menu_id` INT(11) NOT NULL,
  PRIMARY KEY (`permission_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`cms_iplanet_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`cms_iplanet_role` (
  `role_id` INT(11) NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`cms_iplanet_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`cms_iplanet_user` (
  `user_id` INT(11) NOT NULL,
  `user_username` VARCHAR(45) NOT NULL,
  `user_pass` VARCHAR(150) NOT NULL,
  `user_name` VARCHAR(45) NULL DEFAULT NULL,
  `user_mail` VARCHAR(100) NOT NULL,
  `role_id` INT(11) NOT NULL DEFAULT '0',
  `user_photo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`detalle_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`detalle_tipo` (
  `id_tipo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`detalle` (
  `id_complemtno` INT(11) NOT NULL,
  `id_documento` INT(11) NOT NULL,
  `id_tipo_complemento` INT(11) NOT NULL COMMENT 'hecho, peticion, adjunto',
  `complemento` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_complemtno`),
  INDEX `fk_complemento_a_documento_idx` (`id_documento` ASC) VISIBLE,
  INDEX `fk_complemento_a_tipo_idx` (`id_tipo_complemento` ASC) VISIBLE,
  CONSTRAINT `fk_complemento_a_documento`
    FOREIGN KEY (`id_documento`)
    REFERENCES `cespidh_cms`.`documento` (`id_documento`),
  CONSTRAINT `fk_complemento_a_tipo`
    FOREIGN KEY (`id_tipo_complemento`)
    REFERENCES `cespidh_cms`.`detalle_tipo` (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`derecho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`derecho` (
  `id_derecho` INT(11) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `formato_derecho` TEXT NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `posicion` INT(11) NOT NULL,
  `tipo` ENUM('nulo', 'multiple', 'solo una opcion') NULL DEFAULT NULL,
  PRIMARY KEY (`id_derecho`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`derecho_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`derecho_detalle` (
  `id_derecho_detalle` INT(11) NOT NULL,
  `id_derecho` INT(11) NULL DEFAULT NULL,
  `nombre_detalle` VARCHAR(45) NULL DEFAULT NULL,
  `formato_derecho` TEXT NULL DEFAULT NULL,
  `estado` ENUM('Activo', 'Inactivo') NULL DEFAULT NULL,
  `posicion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_derecho_detalle`),
  INDEX `fk_derecho_detalle_id_derecho_idx` (`id_derecho` ASC) VISIBLE,
  CONSTRAINT `fk_derecho_detalle_id_derecho`
    FOREIGN KEY (`id_derecho`)
    REFERENCES `cespidh_cms`.`derecho` (`id_derecho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`complemento_derecho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`complemento_derecho` (
  `id_complemento_derecho` INT(11) NOT NULL,
  `id_derecho_detalle` INT(11) NOT NULL,
  `id_derecho` INT(11) NOT NULL,
  `complemento` TEXT NULL DEFAULT NULL,
  `detalle_id_complemtno` INT(11) NOT NULL,
  PRIMARY KEY (`id_complemento_derecho`),
  INDEX `fk_complemento_derecho_ide_derecho_detalle_idx` (`id_derecho_detalle` ASC) VISIBLE,
  INDEX `fk_complemento_id_derecho_idx` (`id_derecho` ASC) VISIBLE,
  INDEX `fk_complemento_derecho_detalle1_idx` (`detalle_id_complemtno` ASC) VISIBLE,
  CONSTRAINT `fk_complemento_derecho_ide_derecho_detalle`
    FOREIGN KEY (`id_derecho_detalle`)
    REFERENCES `cespidh_cms`.`derecho_detalle` (`id_derecho_detalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complemento_id_derecho`
    FOREIGN KEY (`id_derecho`)
    REFERENCES `cespidh_cms`.`derecho` (`id_derecho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complemento_derecho_detalle1`
    FOREIGN KEY (`detalle_id_complemtno`)
    REFERENCES `cespidh_cms`.`detalle` (`id_complemtno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`denuncia_corrupcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`denuncia_corrupcion` (
  `id` INT(11) NOT NULL,
  `saludo` VARCHAR(255) NULL DEFAULT NULL,
  `asunto` VARCHAR(255) NOT NULL,
  `introduccion` TEXT NOT NULL,
  `hecho` VARCHAR(255) NOT NULL,
  `presunto_infractor` VARCHAR(255) NOT NULL,
  `peticiones` VARCHAR(255) NOT NULL,
  `peticiones_descripcion` TEXT NULL DEFAULT NULL,
  `pruebas` VARCHAR(255) NOT NULL,
  `notificacion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`denuncia_general`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`denuncia_general` (
  `id` INT(10) UNSIGNED NOT NULL,
  `asunto` VARCHAR(255) NOT NULL,
  `saludo` VARCHAR(255) NULL DEFAULT NULL,
  `introduccion` TEXT NOT NULL,
  `hecho` VARCHAR(255) NOT NULL,
  `identificacion_producto` VARCHAR(255) NOT NULL,
  `presunto_agresor` VARCHAR(255) NOT NULL,
  `peticion` VARCHAR(255) NOT NULL,
  `peticion_descripcion` TEXT NULL DEFAULT NULL,
  `pruebas` VARCHAR(255) NOT NULL,
  `notificacion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`derecho_peticion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`derecho_peticion` (
  `id` INT(11) NOT NULL,
  `asunto` VARCHAR(255) NOT NULL,
  `saludo` VARCHAR(255) NULL DEFAULT NULL,
  `introduccion` TEXT NULL DEFAULT NULL,
  `hecho` VARCHAR(255) NULL DEFAULT NULL,
  `hecho_descripcion` TEXT NULL DEFAULT NULL,
  `peticiones` VARCHAR(255) NULL DEFAULT NULL,
  `pruebas` VARCHAR(255) NULL DEFAULT NULL,
  `notificacion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`destino` (
  `id_destino` INT(11) NOT NULL,
  `id_documento` INT(11) NOT NULL,
  `des_entidad` VARCHAR(100) NULL DEFAULT NULL,
  `des_persona` VARCHAR(100) NULL DEFAULT NULL,
  `des_correo` VARCHAR(100) NULL DEFAULT NULL,
  `des_direccion` VARCHAR(100) NULL DEFAULT NULL,
  `des_telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_destino`),
  INDEX `fk_destino_a_documento_idx` (`id_documento` ASC) VISIBLE,
  CONSTRAINT `fk_destino_a_documento`
    FOREIGN KEY (`id_documento`)
    REFERENCES `cespidh_cms`.`documento` (`id_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`formato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`formato` (
  `id_formato` INT(11) NOT NULL,
  `documento_tipo_id` INT(11) NULL DEFAULT NULL,
  `asunto` TEXT NOT NULL,
  `saludo` TEXT NULL DEFAULT NULL,
  `bloque1` TEXT NULL DEFAULT NULL,
  `bloque2` TEXT NULL DEFAULT NULL,
  `despedida` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_formato`),
  INDEX `fk_formato_documento_tipo_id_idx` (`documento_tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_formato_documento_tipo_id`
    FOREIGN KEY (`documento_tipo_id`)
    REFERENCES `cespidh_cms`.`documento_tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`pdf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`pdf` (
  `id` INT(11) NOT NULL,
  `header` VARCHAR(255) NULL DEFAULT NULL,
  `encabezado_texto` TEXT NOT NULL,
  `footer` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`sitio_about`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`sitio_about` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(120) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `titulo_2` VARCHAR(120) NOT NULL,
  `subtitulo` VARCHAR(120) NOT NULL,
  `descripcion_2` TEXT NOT NULL,
  `foto` VARCHAR(120) NOT NULL,
  `titulo_3` VARCHAR(120) NOT NULL,
  `indicador_1` VARCHAR(120) NOT NULL,
  `valor_1` INT(11) NOT NULL,
  `indicador_2` VARCHAR(120) NOT NULL,
  `valor_2` INT(11) NOT NULL,
  `indicador_3` VARCHAR(120) NOT NULL,
  `valor_3` INT(11) NOT NULL,
  `indicador_4` VARCHAR(120) NOT NULL,
  `valor_4` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`sitio_articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`sitio_articulos` (
  `id_articulo` INT(11) NOT NULL,
  `id_seccion` INT(11) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  `titulo` VARCHAR(120) NULL DEFAULT NULL,
  `foto` VARCHAR(120) NULL DEFAULT NULL,
  `descripcion_corta` VARCHAR(200) NULL DEFAULT NULL,
  `descripcion_completa` TEXT NULL DEFAULT NULL,
  `autor` VARCHAR(120) NULL DEFAULT NULL,
  `fecha_publicacion` DATE NULL DEFAULT NULL,
  `tags` VARCHAR(255) NULL DEFAULT NULL,
  `archivo` VARCHAR(120) NULL DEFAULT NULL,
  `titulo_archivo` VARCHAR(120) NULL DEFAULT NULL,
  `estado` ENUM('Activo', 'Inactivo') NULL DEFAULT NULL,
  PRIMARY KEY (`id_articulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`sitio_banner_home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`sitio_banner_home` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(60) NOT NULL,
  `icono` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(120) NOT NULL,
  `boton_texto` VARCHAR(30) NOT NULL,
  `boton_link` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`sitio_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`sitio_categorias` (
  `id_categoria` INT(11) NOT NULL,
  `titulo` VARCHAR(120) NOT NULL,
  `foto` VARCHAR(120) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `icono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`sitio_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`sitio_contacto` (
  `id` INT(11) NOT NULL,
  `icono1` VARCHAR(30) NOT NULL,
  `titulo1` VARCHAR(50) NOT NULL,
  `mensaje1` VARCHAR(100) NOT NULL,
  `icono2` VARCHAR(30) NOT NULL,
  `titulo2` VARCHAR(50) NOT NULL,
  `mensaje2` VARCHAR(100) NOT NULL,
  `icono3` VARCHAR(30) NOT NULL,
  `titulo3` VARCHAR(50) NOT NULL,
  `mensaje3` VARCHAR(100) NOT NULL,
  `titulo_formulario` VARCHAR(50) NOT NULL,
  `mesaje_formulario` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`sitio_general`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`sitio_general` (
  `id` INT(11) NOT NULL,
  `pagina_titulo` VARCHAR(200) NOT NULL,
  `pagina_descripcion` VARCHAR(255) NOT NULL,
  `pagina_keywords` VARCHAR(255) NOT NULL,
  `link_face` VARCHAR(255) NOT NULL,
  `link_twitter` VARCHAR(255) NOT NULL,
  `link_linkedin` VARCHAR(255) NOT NULL,
  `link_instagram` VARCHAR(150) NOT NULL,
  `texto_consulta` VARCHAR(255) NOT NULL,
  `texto_calendario` VARCHAR(255) NOT NULL,
  `whatsapp` VARCHAR(20) NOT NULL,
  `whatsapp_mensaje` VARCHAR(100) NOT NULL,
  `logo` VARCHAR(255) NOT NULL,
  `texto_footer` TEXT NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `titulo_vision` VARCHAR(120) NOT NULL,
  `texto_vision` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`sitio_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`sitio_menu` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(60) NOT NULL,
  `titulo_practicas` VARCHAR(60) NOT NULL,
  `titulo_noticias` VARCHAR(60) NOT NULL,
  `titulo_publicaciones` VARCHAR(60) NOT NULL,
  `titulo_contacto` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`sitio_secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`sitio_secciones` (
  `id_seccion` INT(11) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `icono` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_seccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`sitio_sliders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`sitio_sliders` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `foto` VARCHAR(200) NOT NULL,
  `mensaje_1` VARCHAR(200) NOT NULL,
  `mensaje_2` VARCHAR(200) NOT NULL,
  `mensaje_3` VARCHAR(200) NOT NULL,
  `mensaje_boton` VARCHAR(40) NOT NULL,
  `link` VARCHAR(200) NOT NULL,
  `posicion` INT(11) NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `tipo_slider` ENUM('Izquierda', 'Centro', 'Derecha') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`sitio_sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`sitio_sucursales` (
  `id_sucursal` INT(11) NOT NULL,
  `nombre_sucursal` VARCHAR(120) NOT NULL,
  `ubicacion` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(120) NOT NULL,
  `correo` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id_sucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`solicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`solicitante` (
  `id_solicitante` INT(11) NOT NULL,
  `id_documento` INT(11) NOT NULL,
  `id_genero` INT(11) NOT NULL,
  `id_grupo` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `cedula` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `autoriza_firma` VARCHAR(2) NULL DEFAULT NULL,
  `autoriza_terminos` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_solicitante`),
  INDEX `fk_solicitante_a_genero_idx` (`id_genero` ASC) VISIBLE,
  INDEX `fk_solicitante_a_grupo_idx` (`id_grupo` ASC) VISIBLE,
  INDEX `fk_solicitante_a_dcocumento_idx` (`id_documento` ASC) VISIBLE,
  CONSTRAINT `fk_solicitante_a_dcocumento`
    FOREIGN KEY (`id_documento`)
    REFERENCES `cespidh_cms`.`documento` (`id_documento`),
  CONSTRAINT `fk_solicitante_a_genero`
    FOREIGN KEY (`id_genero`)
    REFERENCES `cespidh_cms`.`solicitante_genero` (`id_genero`),
  CONSTRAINT `fk_solicitante_a_grupo`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `cespidh_cms`.`solicitante_grupo` (`id_grupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`terminos_legales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`terminos_legales` (
  `id_termino_legal` INT(11) NOT NULL,
  `tipo` ENUM('Autorización de firma', 'Terminos y Condiciones') NOT NULL,
  `contenido` TEXT NOT NULL,
  PRIMARY KEY (`id_termino_legal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`tutela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`tutela` (
  `id` INT(10) UNSIGNED NOT NULL,
  `accionante` VARCHAR(255) NOT NULL,
  `accionado` VARCHAR(255) NOT NULL,
  `asunto` VARCHAR(255) NOT NULL,
  `introduccion` TEXT NOT NULL,
  `hechos` VARCHAR(255) NOT NULL,
  `derechos_vulnerados` VARCHAR(255) NOT NULL,
  `derechos_vulnerados_descricion` TEXT NOT NULL,
  `fundamentos_juridicos` VARCHAR(255) NOT NULL,
  `fundamentos_juridicos_descripcion` TEXT NULL DEFAULT NULL,
  `pruebas` VARCHAR(255) NOT NULL,
  `pruebas_descripcion` TEXT NOT NULL,
  `pretensiones` VARCHAR(255) NOT NULL,
  `pretenciones_descripcion` TEXT NOT NULL,
  `fundamentos_de_derecho` VARCHAR(255) NOT NULL,
  `fundamentos_de_derecho_descripcion` TEXT NOT NULL,
  `anexos` VARCHAR(255) NOT NULL,
  `anexos_descripcion` TEXT NULL DEFAULT NULL,
  `juramento` VARCHAR(255) NOT NULL,
  `juramento_descripcion` TEXT NOT NULL,
  `demandante` VARCHAR(255) NOT NULL,
  `demandado` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`web_iplanet_about`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`web_iplanet_about` (
  `about_id` INT(11) NOT NULL,
  `about_title` VARCHAR(100) NOT NULL,
  `about_description` TEXT NULL DEFAULT NULL,
  `about_img` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`about_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`web_iplanet_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`web_iplanet_article` (
  `article_id` INT(11) NOT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  `article_img` VARCHAR(100) NULL DEFAULT NULL,
  `article_title` VARCHAR(255) NULL DEFAULT NULL,
  `article_description` TEXT NULL DEFAULT NULL,
  `article_active` ENUM('Si', 'NO') NULL DEFAULT NULL,
  `article_outstanding` ENUM('primario', 'secundario') NULL DEFAULT NULL,
  PRIMARY KEY (`article_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`web_iplanet_carousel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`web_iplanet_carousel` (
  `carousel_id` INT(11) NOT NULL,
  `carousel_img` VARCHAR(255) NULL DEFAULT NULL,
  `carousel_title` VARCHAR(100) NULL DEFAULT NULL,
  `carousel_position` INT(2) NULL DEFAULT NULL,
  `carousel_active` ENUM('Si', 'No') NULL DEFAULT NULL,
  `carousel_description` TEXT NULL DEFAULT NULL,
  `carousel_button_active` ENUM('Si', 'No') NULL DEFAULT NULL,
  `carousel_button_text` VARCHAR(30) NULL DEFAULT NULL,
  `carousel_button_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`carousel_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`web_iplanet_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`web_iplanet_category` (
  `category_id` INT(11) NOT NULL,
  `category_title` VARCHAR(100) NOT NULL,
  `category_description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`web_iplanet_general`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`web_iplanet_general` (
  `general_id` INT(11) NOT NULL,
  `general_logo` VARCHAR(100) NULL DEFAULT NULL,
  `general_description` TEXT NULL DEFAULT NULL,
  `general_keyword` VARCHAR(255) NULL DEFAULT NULL,
  `general_address` VARCHAR(255) NULL DEFAULT NULL,
  `general_telephone` VARCHAR(50) NULL DEFAULT NULL,
  `general_email` VARCHAR(150) NULL DEFAULT NULL,
  `general_twitter` VARCHAR(150) NULL DEFAULT NULL,
  `general_facebook` VARCHAR(150) NULL DEFAULT NULL,
  `general_instagram` VARCHAR(150) NULL DEFAULT NULL,
  `general_linkedin` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`general_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`web_iplanet_navbar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`web_iplanet_navbar` (
  `navbar_id` INT(11) NOT NULL,
  `navbar_option` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`navbar_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`web_iplanet_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`web_iplanet_section` (
  `section_id` INT(11) NOT NULL,
  `section_title` VARCHAR(100) NULL DEFAULT NULL,
  `section_description` TEXT NULL DEFAULT NULL,
  `section_card_img` VARCHAR(100) NULL DEFAULT NULL,
  `section_card_title` VARCHAR(100) NULL DEFAULT NULL,
  `section_card_description` VARCHAR(200) NULL DEFAULT NULL,
  `section_card_button_url` VARCHAR(100) NULL DEFAULT NULL,
  `section_card2_img` VARCHAR(100) NULL DEFAULT NULL,
  `section_card2_title` VARCHAR(100) NULL DEFAULT NULL,
  `section_card2_description` VARCHAR(200) NULL DEFAULT NULL,
  `section_card2_button_url` VARCHAR(100) NULL DEFAULT NULL,
  `section_card3_img` VARCHAR(100) NULL DEFAULT NULL,
  `section_card3_title` VARCHAR(100) NULL DEFAULT NULL,
  `section_card3_description` VARCHAR(200) NULL DEFAULT NULL,
  `section_card3_button_url` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`section_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`derecho_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`derecho_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle_tipo_id_tipo` INT(11) NOT NULL,
  `derecho_id_derecho` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_derecho_type_detalle_tipo1_idx` (`detalle_tipo_id_tipo` ASC) VISIBLE,
  INDEX `fk_derecho_type_derecho1_idx` (`derecho_id_derecho` ASC) VISIBLE,
  CONSTRAINT `fk_derecho_type_detalle_tipo1`
    FOREIGN KEY (`detalle_tipo_id_tipo`)
    REFERENCES `cespidh_cms`.`detalle_tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_derecho_type_derecho1`
    FOREIGN KEY (`derecho_id_derecho`)
    REFERENCES `cespidh_cms`.`derecho` (`id_derecho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`formulario_step_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`formulario_step_2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `formulario_id_formulario` INT(11) NOT NULL,
  `detalle_tipo_id_tipo` INT(11) NOT NULL,
  `orden` INT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formulario_step_2_formulario1_idx` (`formulario_id_formulario` ASC) VISIBLE,
  INDEX `fk_formulario_step_2_detalle_tipo1_idx` (`detalle_tipo_id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_formulario_step_2_formulario1`
    FOREIGN KEY (`formulario_id_formulario`)
    REFERENCES `cespidh_cms`.`formulario` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_step_2_detalle_tipo1`
    FOREIGN KEY (`detalle_tipo_id_tipo`)
    REFERENCES `cespidh_cms`.`detalle_tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`detalles_entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`detalles_entidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`formulario_step_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`formulario_step_1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `obligatorio` ENUM('Si', 'No') NULL,
  `orden` INT NULL,
  `detalles_entidad_id` INT NOT NULL,
  `formulario_id_formulario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formulario_step_1_detalles_entidad1_idx` (`detalles_entidad_id` ASC) VISIBLE,
  INDEX `fk_formulario_step_1_formulario1_idx` (`formulario_id_formulario` ASC) VISIBLE,
  CONSTRAINT `fk_formulario_step_1_detalles_entidad1`
    FOREIGN KEY (`detalles_entidad_id`)
    REFERENCES `cespidh_cms`.`detalles_entidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_step_1_formulario1`
    FOREIGN KEY (`formulario_id_formulario`)
    REFERENCES `cespidh_cms`.`formulario` (`id_formulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`work` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL,
  `finish_at` DATETIME NULL,
  `observation` TEXT NULL,
  `document` VARCHAR(45) NULL,
  `documento_id_documento` INT(11) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  `work_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_work_documento1_idx` (`documento_id_documento` ASC) VISIBLE,
  INDEX `fk_work_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_work_work_type1_idx` (`work_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_work_documento1`
    FOREIGN KEY (`documento_id_documento`)
    REFERENCES `cespidh_cms`.`documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cespidh_v1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_work_work_type1`
    FOREIGN KEY (`work_type_id`)
    REFERENCES `cespidh_cms`.`work_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`complemento_formulario_step_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`complemento_formulario_step_1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `formulario_step_1_id` INT NOT NULL,
  `detalle_tipo_id_tipo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_complemento_formulario_step_1_formulario_step_11_idx` (`formulario_step_1_id` ASC) VISIBLE,
  INDEX `fk_complemento_formulario_step_1_detalle_tipo1_idx` (`detalle_tipo_id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_complemento_formulario_step_1_formulario_step_11`
    FOREIGN KEY (`formulario_step_1_id`)
    REFERENCES `cespidh_cms`.`formulario_step_1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complemento_formulario_step_1_detalle_tipo1`
    FOREIGN KEY (`detalle_tipo_id_tipo`)
    REFERENCES `cespidh_cms`.`detalle_tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cespidh_cms`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cespidh_cms`.`respuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preguntas_id` INT NOT NULL,
  `pregunta_detalle_id` INT NOT NULL,
  `documento_id_documento` INT(11) NOT NULL,
  `formulario_id` INT NULL,
  `secciones_id` INT NULL,
  `respuesta` VARCHAR(45) NULL,
  `documento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_respuestas_preguntas1_idx` (`preguntas_id` ASC) VISIBLE,
  INDEX `fk_respuestas_pregunta_detalle1_idx` (`pregunta_detalle_id` ASC) VISIBLE,
  INDEX `fk_respuestas_formulario_idx` (`formulario_id` ASC) VISIBLE,
  INDEX `fk_respuesta_secciones_idx` (`secciones_id` ASC) VISIBLE,
  INDEX `fk_respuestas_documento1_idx` (`documento_id_documento` ASC) VISIBLE,
  CONSTRAINT `fk_respuestas_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `cespidh_cms`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_pregunta_detalle1`
    FOREIGN KEY (`pregunta_detalle_id`)
    REFERENCES `cespidh_cms`.`pregunta_detalle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_formulario`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `cespidh_cms`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuesta_secciones`
    FOREIGN KEY (`secciones_id`)
    REFERENCES `cespidh_cms`.`preguntas` (`secciones_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_documento1`
    FOREIGN KEY (`documento_id_documento`)
    REFERENCES `cespidh_cms`.`documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
